### ISSUE TITLE
Uncaught Error: EPERM, operation not permitted 'D:\code\...'

### ISSUE THREAD

**Issue by SgtPooki** [rgbkrk/atom-achievements#17]
[Enter steps to reproduce below:]

1. I deleted a folder of files from my terminal. They were still open in atom.
2. closing and reopening atom seems to have resolved the popups.

**Atom Version**: 0.177.0
**System**: Microsoft Windows 8.1
**Thrown From**: [achievements](https://github.com/rgbkrk/atom-achievements) package, v0.7.0

### Stack Trace

Uncaught Error: EPERM, operation not permitted 'D:\code\...'

```
At C:\Users\Russell Dempsey\AppData\Local\atom\app-0.177.0\resources\app\node_modules\pathwatcher\lib\file.js:318

Error: EPERM, operation not permitted 'D:\code\...'
  at Error (native)
  at Object.fs.mkdirSync (fs.js:752:18)
  at Function.sync (C:\Users\Russell Dempsey\AppData\Local\atom\app-0.177.0\resources\app\node_modules\mkdirp\index.js:55:12)
  at Object.fsPlus.writeFileSync (C:\Users\Russell Dempsey\AppData\Local\atom\app-0.177.0\resources\app\node_modules\fs-plus\lib\fs-plus.js:227:14)
  at File.module.exports.File.writeFileSync (C:\Users\Russell Dempsey\AppData\Local\atom\app-0.177.0\resources\app\node_modules\pathwatcher\lib\file.js:234:19)
  at File.module.exports.File.writeFileWithPrivilegeEscalationSync (C:\Users\Russell Dempsey\AppData\Local\atom\app-0.177.0\resources\app\node_modules\pathwatcher\lib\file.js:304:21)
  at File.module.exports.File.write (C:\Users\Russell Dempsey\AppData\Local\atom\app-0.177.0\resources\app\node_modules\pathwatcher\lib\file.js:293:12)
  at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\Russell Dempsey\AppData\Local\atom\app-0.177.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:970:17)
  at TextBuffer.module.exports.TextBuffer.save (C:\Users\Russell Dempsey\AppData\Local\atom\app-0.177.0\resources\app\node_modules\text-buffer\lib\text-buffer.js:958:19)
  at TextEditor.module.exports.TextEditor.save (C:\Users\Russell Dempsey\AppData\Local\atom\app-0.177.0\resources\app\src\text-editor.js:620:26)
  at Object.module.exports.autosavePaneItem (C:\Users\Russell Dempsey\AppData\Local\atom\app-0.177.0\resources\app\node_modules\autosave\lib\autosave.js:56:80)
  at Object.module.exports.autosaveAllPaneItems (C:\Users\Russell Dempsey\AppData\Local\atom\app-0.177.0\resources\app\node_modules\autosave\lib\autosave.js:64:28)
  at C:\Users\Russell Dempsey\AppData\Local\atom\app-0.177.0\resources\app\node_modules\autosave\lib\autosave.js:25:26

```

### Commands

```
     -2:48.4 project-find:show (atom-text-editor.editor)
     -2:44.9 core:confirm (atom-text-editor.editor.mini)
     -1:59.9 editor:consolidate-selections (atom-text-editor.editor.mini)
     -1:59.9 core:cancel (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
achievements, v0.7.0
atom-beautify, v0.21.2
atom-jasmine, v0.5.0
atom-jshint, v1.5.0
autocomplete-plus, v2.0.12
autocomplete-snippets, v1.0.1
docblockr, v0.5.8
editor-stats, v0.17.0
editorconfig, v0.3.0
git-log, v0.2.0
git-tab-status, v1.5.3
highlight-column, v0.3.2
highlight-line, v0.9.3
irc, v0.2.9
js-refactor, v0.3.0
jshint, v1.2.0
line-ending-converter, v1.0.0
linter, v0.11.1
linter-csslint, v0.0.11
minimap, v4.1.0
project-manager, v1.15.5
refactor, v0.4.1
seti-ui, v0.6.3
tabs-to-spaces, v0.8.1
trailing-spaces, v0.2.4

# Dev
No dev packages
```

/cc @atom/core

**Comment by SgtPooki** [comment]
eh. Maintainer, if you could remove the project name I would greatly appreciate it.

**Comment by rgbkrk** [comment]
It doesn't seem like @github lets me remove when you changed the title. Eek!

**Comment by SgtPooki** [comment]
Yea and I missed it.. eh.

**Comment by SgtPooki** [comment]
Can you delete the comment above?
