### ISSUE TITLE
Failed to activate the achievements package

### ISSUE THREAD

**Issue by fuzzyweapon** [rgbkrk/atom-achievements#19]
[Enter steps to reproduce below:]

1. Fire up Atom (version 0.187.0) on OS X 10.9.5.
2. Install achievements from the package installer.

**Atom Version**: 0.187.0
**System**: Mac OS X 10.9.5
**Thrown From**: [achievements](https://github.com/rgbkrk/atom-achievements) package, v0.7.0

### Stack Trace

Failed to activate the achievements package

```
At undefined is not a function

TypeError: undefined is not a function
  at AchievementsView.module.exports.AchievementsView.achieve (/Users/jwillson/.atom/packages/achievements/lib/achievements-view.coffee:32:40)
  at Achiever.module.exports.Achiever.achieve (/Users/jwillson/.atom/packages/achievements/lib/achiever.coffee:130:25)
  at Achiever.module.exports.Achiever.processUnlock (/Users/jwillson/.atom/packages/achievements/lib/achiever.coffee:99:6)
  at /Users/jwillson/.atom/packages/achievements/lib/achiever.coffee:1:1
  at Atom.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at Object.module.exports.activate (/Users/jwillson/.atom/packages/achievements/lib/achievements.coffee:13:10)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
  4x -0:47.9 core:backspace (atom-text-editor.editor.mini)
  2x -0:46.8 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "underscorejs-snippets"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Search, v0.4.0
achievements, v0.7.0
auto-update-packages, v0.2.2
autocomplete-css, v0.4.0
autocomplete-emojis, v1.0.0
autocomplete-html, v0.3.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.4.1
autocomplete-snippets, v1.0.1
color-picker, v1.4.4
git-tab-status, v1.5.3
javascript-snippets, v1.0.0
linter, v0.12.0
minimap, v4.5.0
sync-settings, v0.2.2
tabs-to-spaces, v0.8.1

# Dev
No dev packages
```

**Comment by rgbkrk** [comment]
Ruh roh, I'm way out of date here then. Thanks for the report!

**Comment by RodrigoEspinosa** [comment]
## Sames here. 


**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.3
**Thrown From**: [achievements](https://github.com/rgbkrk/atom-achievements) package, v0.7.0

### Stack Trace

Failed to activate the achievements package

```
At undefined is not a function

TypeError: undefined is not a function
  at AchievementsView.module.exports.AchievementsView.achieve (/Users/rec/.atom/packages/achievements/lib/achievements-view.coffee:32:40)
  at Achiever.module.exports.Achiever.achieve (/Users/rec/.atom/packages/achievements/lib/achiever.coffee:130:25)
  at Achiever.module.exports.Achiever.processUnlock (/Users/rec/.atom/packages/achievements/lib/achiever.coffee:99:6)
  at /Users/rec/.atom/packages/achievements/lib/achiever.coffee:1:1
  at Atom.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at Object.module.exports.activate (/Users/rec/.atom/packages/achievements/lib/achievements.coffee:13:10)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:214:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:465:21)
  at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:334:19
  at /Applications/Atom.app/Contents/Resources/app/src/config.js:640:20
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/Applications/Atom.app/Contents/Resources/app/src/config.js:804:29)
  at Config.module.exports.Config.setRawValue (/Applications/Atom.app/Contents/Resources/app/src/config.js:617:19)
  at Config.module.exports.Config.set (/Applications/Atom.app/Contents/Resources/app/src/config.js:231:14)
  at Config.module.exports.Config.removeAtKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:409:12)
  at Package.module.exports.Package.enable (/Applications/Atom.app/Contents/Resources/app/src/package.js:152:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:162:14)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-card.js:209:27)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
     -1:27.3 tree-view:toggle (atom-text-editor.editor.is-focused)
     -1:04.6 core:move-to-top (atom-text-editor.editor.is-focused)
  8x -1:04.3 core:close (atom-text-editor.editor.is-focused)
     -0:37.8 settings-view:open (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-quantum-syntax.theme-quantum-ui)
```

### Config

```json
{
  "core": {
    "followSymlinks": true,
    "disabledPackages": [
      "atom-lint",
      "linter-pep8",
      "linter-pylint",
      "python-isort",
      "autocomplete",
      "timekeeper",
      "symbols-view",
      "vim-mode",
      "atom-spotify",
      "color-picker",
      "bower-install",
      "Tern",
      "atom-ctags",
      "atom-wield",
      "terminal-status",
      "autocomplete-jedi",
      "slack-chat",
      "web-view",
      "web-browser"
    ],
    "themes": [
      "quantum-ui",
      "quantum-syntax"
    ],
    "projectHome": "/User/rec/Documents/Projects/rec",
    "excludeVcsIgnoredPaths": false,
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
achievements, v0.7.0
atom-django, v0.2.1
atom-jade, v0.1.0
atom-pair, v1.0.1
atom-ternjs, v0.5.5
auto-update-packages, v0.2.2
autocomplete-paths, v1.0.2
autocomplete-plus, v2.4.2
autocomplete-snippets, v1.0.1
django-templates, v0.3.0
editorconfig, v0.3.2
emmet, v2.3.4
file-icons, v1.5.1
git-log, v0.3.0
irc, v0.2.9
language-csharp, v0.5.0
language-jade, v0.3.0
language-lua, v0.9.0
language-puppet, v0.10.0
language-restructuredtext, v0.3.0
linter, v0.12.0
linter-csslint, v0.0.11
linter-flake8, v1.3.0
linter-jshint, v0.1.0
minimap, v4.6.0
project-manager, v1.15.5
quantum-syntax, v0.2.1
quantum-ui, v0.2.0
tabs-to-spaces, v0.8.1

# Dev
No dev packages
```

**Comment by fuzzyweapon** [comment]
You're welcome!




*____________________*{*fuzzyweapon}*

*---------------------------------------*

**Comment by travi** [comment]
any update on this?

**Comment by RodrigoEspinosa** [comment]
@travi should be resolved in this pull request https://github.com/rgbkrk/atom-achievements/pull/22

**Comment by phh** [comment]
+1

Would be nice to have this fixed.

**Comment by rgbkrk** [comment]
Just released `v0.7.1` using #22.

I was stunned that there were actual users of this package. I love you all.

![](http://media2.giphy.com/media/ExTYuNCpYVMGY/giphy.gif)

**Comment by jameswlane** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.206.0
**System**: Microsoft Windows 7 Enterprise 
**Thrown From**: [achievements](https://github.com/rgbkrk/atom-achievements) package, v0.7.2


### Stack Trace

Failed to activate the achievements package

```
At undefined is not a function

TypeError: undefined is not a function
  at new Achiever (C:\Users\jl82576\.atom\packages\achievements\lib\achiever.coffee:53:10)
  at Object.module.exports.activate (C:\Users\jl82576\.atom\packages\achievements\lib\achievements.coffee:10:13)
  at Package.module.exports.Package.activateNow (C:\Users\jl82576\AppData\Local\atom\app-0.206.0\resources\app.asar\src\package.js:238:19)
  at C:\Users\jl82576\AppData\Local\atom\app-0.206.0\resources\app.asar\src\package.js:219:30
  at Package.module.exports.Package.measure (C:\Users\jl82576\AppData\Local\atom\app-0.206.0\resources\app.asar\src\package.js:163:15)
  at Package.module.exports.Package.activate (C:\Users\jl82576\AppData\Local\atom\app-0.206.0\resources\app.asar\src\package.js:211:14)
  at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\jl82576\AppData\Local\atom\app-0.206.0\resources\app.asar\src\package-manager.js:451:21)
  at C:\Users\jl82576\AppData\Local\atom\app-0.206.0\resources\app.asar\src\package-manager.js:435:29
  at Config.module.exports.Config.transact (C:\Users\jl82576\AppData\Local\atom\app-0.206.0\resources\app.asar\src\config.js:311:16)
  at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\jl82576\AppData\Local\atom\app-0.206.0\resources\app.asar\src\package-manager.js:430:19)
  at PackageManager.module.exports.PackageManager.activate (C:\Users\jl82576\AppData\Local\atom\app-0.206.0\resources\app.asar\src\package-manager.js:411:46)
  at Atom.module.exports.Atom.startEditorWindow (C:\Users\jl82576\AppData\Local\atom\app-0.206.0\resources\app.asar\src\atom.js:636:21)
  at Object.<anonymous> (C:\Users\jl82576\AppData\Local\atom\app-0.206.0\resources\app.asar\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (C:\Users\jl82576\AppData\Local\atom\app-0.206.0\resources\app.asar\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\jl82576\AppData\Local\atom\app-0.206.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///C:/Users/jl82576/AppData/Local/atom/app-0.206.0/resources/app.asar/static/index.js:95:23)
  at window.onload (file:///C:/Users/jl82576/AppData/Local/atom/app-0.206.0/resources/app.asar/static/index.js:36:7)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
achievements, v0.7.2
atom-jshint, v2.0.0
autocomplete-modules, v0.3.5
autocomplete-paths, v1.0.2
autocomplete-sass, v0.1.0
css-snippets, v0.8.0
git-diff-details, v0.18.0
grunt-runner, v0.10.0
gulp-snippets, v0.6.1
hashrocket, v0.4.8
javascript-snippets, v1.0.0
linter, v0.12.6
linter-bootlint, v0.0.6
linter-csslint, v0.0.13
linter-erb, v0.1.1
linter-eslint, v0.5.8
linter-htmlhint, v0.0.16
linter-javac, v0.1.4
linter-js-standard, v0.2.5
linter-js-yaml, v1.0.1
linter-jscs, v1.12.0
linter-jshint, v0.1.6
linter-jsxhint, v0.1.2
linter-pylint, v0.2.2
linter-ruby, v0.1.6
linter-scalac, v0.3.4
linter-scss-lint, v1.0.4
linter-shellcheck, v0.0.8
linter-tidy, v1.0.1
linter-xmllint, v0.0.6
minimap, v4.9.4
minimap-find-and-replace, v4.2.0
minimap-git-diff, v4.1.3
node-debugger, v1.0.5
project-manager, v1.15.8
react-snippets, v0.1.4
seti-syntax, v0.4.0
seti-ui, v0.7.1
tabs-to-spaces, v0.11.0
terminal-status, v1.6.7
trailing-spaces, v0.3.0
tree-view-git-status, v0.1.1
underscorejs-snippets, v0.2.2

# Dev
No dev packages
```

**Comment by dkarter** [comment]
Immediately after install:

**Atom Version**: 0.211.0
**System**: Mac OS X 10.10.3
**Thrown From**: [achievements](https://github.com/rgbkrk/atom-achievements) package, v0.7.2


### Stack Trace

Failed to activate the achievements package

```
At undefined is not a function

TypeError: undefined is not a function
  at new Achiever (/Users/dkarter/.atom/packages/achievements/lib/achiever.coffee:53:10)
  at Object.module.exports.activate (/Users/dkarter/.atom/packages/achievements/lib/achievements.coffee:10:13)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:362:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:53:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -0:30.3.0 vim-mode:reset-command-mode (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:26.9.0 emmet:decrement-number-by-01 (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:24.9.0 emmet:increment-number-by-01 (atom-text-editor.editor.vim-mode.command-mode.is-focused)
 10x -0:24.5.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:23.1.0 emmet:decrement-number-by-01 (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:22.6.0 emmet:increment-number-by-01 (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:21 vim-mode:move-up (atom-text-editor.editor.vim-mode.command-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "file-icon-supplement",
      "symbols-view",
      "animated-cursor",
      "atom-color-highlight",
      "highlight-column",
      "css-color-underline",
      "color-picker"
    ],
    "themes": [
      "neutron-ui",
      "neutron-syntax"
    ],
    "followSymlinks": true,
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
ScssBundle, v0.5.0
Sublime-Style-Column-Selection, v1.3.0
achievements, v0.7.2
angularjs, v0.3.0
atom-beautify, v0.28.5
atom-color-highlight, v3.0.9
atom-ctags, v4.1.4
autocomplete-paths, v1.0.2
autocomplete-ruby, v0.1.0
block-travel, v1.0.2
copy-to-hipchat, v0.1.0
coverage, v0.6.1
cucumber, v0.5.0
emmet, v2.3.10
file-icons, v1.5.8
git-tab-status, v1.9.2
javascript-snippets, v1.0.0
jsformat, v0.9.0
language-gherkin, v1.0.2
language-haml, v0.21.0
language-rspec, v0.3.0
linter, v1.0.4
linter-erb, v0.1.1
linter-haml, v0.4.0
linter-jshint, v0.1.6
linter-rubocop, v0.2.7
linter-ruby, v0.1.6
linter-scss-lint, v1.0.4
live-archive, v0.1.15
minimap, v4.10.0
minimap-color-highlight, v4.1.4
neutron-syntax, v0.7.0
neutron-ui, v0.4.0
pain-split, v1.4.0
pigments, v0.8.0
pretty-json, v0.3.3
rspec-snippets, v0.4.0
ruby-block, v0.3.4
ruby-block-converter, v3.5.0
symbol-gen, v1.0.0
term2, v0.9.9
trailing-spaces, v0.3.2
travis-ci-status, v0.15.1
vim-mode, v0.53.0
white-cursor, v0.6.0

# Dev
No dev packages
```

**Comment by HerbCSO** [comment]
Still an issue in Atom 1.0.0

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [achievements](https://github.com/rgbkrk/atom-achievements) package, v0.7.2


### Stack Trace

Failed to activate the achievements package

```
At undefined is not a function

TypeError: undefined is not a function
    at new Achiever (/Users/carsten.dreesbach/.atom/packages/achievements/lib/achiever.coffee:49:12)
    at Object.module.exports.activate (/Users/carsten.dreesbach/.atom/packages/achievements/lib/achievements.coffee:8:118)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:436:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:431:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      "._*",
      ".DS_Store",
      "Thumbs.db",
      "target"
    ]
  },
  "achievements": {}
}
```

### Installed Packages

```coffee
# User
achievements, v0.7.2
atom-pair, v1.1.6
auto-update-packages, v1.0.0
color-picker, v2.0.7
command-logger, v0.23.0
editor-stats, v0.17.0
emmet, v2.3.10
file-icons, v1.5.8
language-applescript, v0.2.0
linter, v1.0.4
linter-javac, v0.1.4
linter-rubocop, v0.2.7
minimap, v4.10.0
search, v0.5.0
terminal-status, v1.6.8

# Dev
No dev packages
```

**Comment by adiq** [comment]
Same on Windows.

1. Install atom
2. Install pkg
3. Run atom

**Atom Version**: 1.0.0
**System**: Windows 7 x64
**Thrown From**: [achievements](https://github.com/rgbkrk/atom-achievements) package, v0.7.2


### Stack Trace

Failed to activate the achievements package

```
At undefined is not a function

TypeError: undefined is not a function
    at new Achiever (C:\Users\Adrian Zmenda\.atom\packages\achievements\lib\achiever.coffee:49:12)
    at Object.module.exports.activate (C:\Users\Adrian Zmenda\.atom\packages\achievements\lib\achievements.coffee:8:118)
    at Package.module.exports.Package.activateNow (C:\Users\Adrian Zmenda\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:240:19)
    at C:\Users\Adrian Zmenda\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:221:30
    at Package.module.exports.Package.measure (C:\Users\Adrian Zmenda\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:165:15)
    at Package.module.exports.Package.activate (C:\Users\Adrian Zmenda\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package.js:213:14)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Adrian Zmenda\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package-manager.js:452:21)
    at C:\Users\Adrian Zmenda\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package-manager.js:436:29
    at Config.module.exports.Config.transact (C:\Users\Adrian Zmenda\AppData\Local\atom\app-1.0.0\resources\app.asar\src\config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\Adrian Zmenda\AppData\Local\atom\app-1.0.0\resources\app.asar\src\package-manager.js:431:19)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
achievements, v0.7.2
autocomplete-php, v0.3.6
color-picker, v2.0.7
emmet, v2.3.12
linter-php, v0.0.15
pigments, v0.8.2

# Dev
No dev packages
```

**Comment by VaughnGH** [comment]
[Enter steps to reproduce below:]
Issue happened upon install and initial enable. I want my CoderScore pts! 

**Atom Version**: 1.0.0
**System**: Ubuntu 14.04.2
**Thrown From**: [achievements](https://github.com/rgbkrk/atom-achievements) package, v0.7.2


### Stack Trace

Failed to activate the achievements package

```
At undefined is not a function

TypeError: undefined is not a function
  at new Achiever (/home/vganemhaka/.atom/packages/achievements/lib/achiever.coffee:53:10)
  at Object.module.exports.activate (/home/vganemhaka/.atom/packages/achievements/lib/achievements.coffee:10:13)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:240:19)
  at /usr/share/atom/resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:452:21)
  at /usr/share/atom/resources/app.asar/src/package-manager.js:313:19
  at /usr/share/atom/resources/app.asar/src/config.js:574:20
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app.asar/src/config.js:736:29)
  at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app.asar/src/config.js:551:19)
  at Config.module.exports.Config.set (/usr/share/atom/resources/app.asar/src/config.js:233:14)
  at Config.module.exports.Config.removeAtKeyPath (/usr/share/atom/resources/app.asar/src/config.js:343:12)
  at Package.module.exports.Package.enable (/usr/share/atom/resources/app.asar/src/package.js:150:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:142:14)
  at HTMLButtonElement.<anonymous> (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-card.js:310:27)
  at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -8:17.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -4:17.6.0 core:move-right (atom-text-editor.editor.mini.is-focused)
  6x -4:17.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
  3x -4:14.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -2:26.1.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:23.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  },
  "achievements": {}
}
```

### Installed Packages

```coffee
# User
achievements, v0.7.2
atom-runner, v2.4.1
autocomplete-python, v0.5.1
linter, v1.2.4
minimap, v4.12.0
pigments, v0.8.4
script-runner, v1.8.3

# Dev
No dev packages
```

**Comment by yetithefoot** [comment]
[Enter steps to reproduce below:]

1. Click install in settings

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.3
**Thrown From**: [achievements](https://github.com/rgbkrk/atom-achievements) package, v0.7.2


### Stack Trace

Failed to activate the achievements package

```
At undefined is not a function

TypeError: undefined is not a function
  at new Achiever (/Users/yeti/.atom/packages/achievements/lib/achiever.coffee:53:10)
  at Object.module.exports.activate (/Users/yeti/.atom/packages/achievements/lib/achievements.coffee:10:13)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:243:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:224:30
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:216:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:486:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:371:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:60:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```

### Commands

```
     -3:09.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -3:07.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:07.5.0 settings-view:open (atom-text-editor.editor)
     -3:04.2.0 editor:delete-to-beginning-of-line (atom-text-editor.editor.mini.is-focused)
  2x -2:59 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:56.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.9.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:00.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "projectHome": "/Users/yeti/Developer/Projects",
    "audioBeep": false,
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
achievements, v0.7.2
autocomplete-paths, v1.0.2
fonts, v0.6.0
git-plus, v5.4.7
language-diff, v0.3.1
linter, v1.5.0
linter-jshint, v1.1.5

# Dev
No dev packages
```

**Comment by bluurn** [comment]
:+1: for this issue :)

**Comment by rgbkrk** [comment]
Finally fixed again, courtesy @bluurn.

Thank you so much!
